package com.grade.entity;
// Generated 2019-1-10 21:50:43 by Hibernate Tools 3.5.0.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class Grade implements java.io.Serializable {

	private Integer gid;
	private String gname;
	private Set studentses = new HashSet(0);

	public Grade() {
	}

	public Grade(String gname) {
		this.gname = gname;
	}

	public Grade(String gname, Set studentses) {
		this.gname = gname;
		this.studentses = studentses;
	}

	public Integer getGid() {
		return this.gid;
	}

	public void setGid(Integer gid) {
		this.gid = gid;
	}

	public String getGname() {
		return this.gname;
	}

	public void setGname(String gname) {
		this.gname = gname;
	}

	public Set getStudentses() {
		return this.studentses;
	}

	public void setStudentses(Set studentses) {
		this.studentses = studentses;
	}

}
